### PR TITLE
Fix 印象笔记 authentication(chinese evernote)

### LINKED ISSUE #6171: Can't login to 印象笔记（Evernote，China）
* KOReader version:2020.04.1
* Device:kindle pw4

#### Issue
Can't login to 印象笔记（Evernote，China）

Open Epub or PDF -> Login to 印象笔记（Evernote，China） -> An error occurred while loggin in:
plugins/evernote.koplugin/EvernoteOAuth.lua:280: Target URL was not found in the response on login

### PR DESCRIPTION
**Pull request by Galunid**
This disables 2fa for evernote(it was never properly implemeneted).
Current 印象笔记 api redirects on login(HTTP code 302), which was
used to detect when 2fa was required. It fixes https://github.com/koreader/koreader/issues/6171
closes https://github.com/koreader/koreader/issues/6171

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/evernote-sdk-lua/3)

### CODE REVIEW

File: EvernoteOAuth.lua [hunk 1]
```diff
@@ -320,10 +320,6 @@ function OAuth:login()
     error("Target URL was not found in the response on login")
   end
 
-  if code == 302 then
-    return self:handleTwoFactor()
```
Comment (Frenzie) [inline EvernoteOAuth.lua:324]: Since you say it was never implemented, should the whole `handleTwoFactor` function be deleted?

Comment (Galunid) [reply EvernoteOAuth.lua:324]: Actually yes, it can be completely removed

**Review by Frenzie — APPROVED** [review]
Seems fine to me

**Comment by Galunid** [comment]
@Frenzie Pinging, in case you forgot :)
